nelmio_api_doc:
    documentation:
        info:
            title: Restaurant API
            description: Documentation de l'API de l'ECF Vite et Gourmand
            version: 1.0.0

        components:
            securitySchemes:
                X-AUTH-TOKEN:
                    type: apiKey
                    name: X-AUTH-Token
                    in: header

        security:
            - X-AUTH-TOKEN: []

    areas:
        path_patterns:
            - ^/api(?!/doc$)
