security:
  role_hierarchy:
    ROLE_ADMIN: [ROLE_EMPLOYE, ROLE_CLIENT]
    ROLE_EMPLOYE: [ROLE_CLIENT]

  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_profiler|_wdt|assets|build)/
      security: false

    main:
      lazy: true
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: app_api_login
      custom_authenticator: App\Security\ApiTokenAuthenticator

  # Note: Only the *first* matching rule is applied (ORDER MATTERS)
  access_control:
    # Swagger / doc : public
    - { path: ^/api/doc, roles: PUBLIC_ACCESS }
    - { path: ^/api/doc\.json, roles: PUBLIC_ACCESS }
    - { path: ^/api/menus$, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api/menus/\d+$, roles: PUBLIC_ACCESS, methods: [GET] }

    # Auth + inscription : public
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/registration, roles: PUBLIC_ACCESS }
    - { path: ^/api/forgot-password, roles: PUBLIC_ACCESS }
    - { path: ^/api/reset-password, roles: PUBLIC_ACCESS }


    # Admin : gestion des comptes (création employés, désactivation, etc.)
    - { path: ^/api/users, roles: ROLE_ADMIN }

    # Compte connecté (token)
    - { path: ^/api/account, roles: IS_AUTHENTICATED_FULLY }

    - { path: ^/api/contact, roles: PUBLIC_ACCESS, methods: [POST] }

    # Avis (Home) : public
    - { path: ^/api/reviews/validated, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api/reviews, roles: PUBLIC_ACCESS }

    # Avis (modération) : employé/admin
    - { path: ^/api/reviews/pending, roles: ROLE_EMPLOYE }
    - { path: ^/api/reviews/\d+/(validate|refuse)$, roles: ROLE_EMPLOYE }

    # Tout le reste de l’API : connecté minimum
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
